spring:
  batch:
    job:
      enabled: false  # 앱 시작 시 자동 실행 끄기
    jdbc:
      initialize-schema: always  # 메타 테이블 자동 생성

  datasource:
    url: jdbc:mysql://localhost:3306/settlement_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

server:
  port: 8082

logging:
  level:
    com.card.payment: DEBUG

# 승인/결제 서비스 설정
approval:
  service:
    url: http://192.168.0.23:8081