spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billing_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

server:
  port: 8083

logging:
  level:
    com.card.payment: DEBUG

# 승인/결제 서비스 설정
approval:
  service:
    url: http://192.168.0.23:8081 # TODO: 주소 동적 변수로 변경 

